New Editable Data
VolkovLabs/business-table pull request #133
Opened 2024-10-24 09:46 UTC by vitPinchuk

Resolves: #103

2024-10-24 09:52 UTC, asimonok requested changes

2024-10-24 09:52 UTC, asimonok commented on src/types/column-editor.ts
> +  rows?: number;
rows should be required

2024-10-24 09:52 UTC, asimonok commented on src/types/column-editor.ts
> +  TEXT_AREA = 'textArea',
please rename to `textarea`

2024-10-24 10:39 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-10-26 12:22 UTC, mikhail-vl approved these changes
Looks good!

2024-10-26 12:22 UTC, merged