Add customization for column header
VolkovLabs/business-table pull request #141
Opened 2024-10-28 05:47 UTC by vitPinchuk

Resolves: #10 
Resolves: #48

2024-10-28 12:55 UTC, vitPinchuk commented
@asimonok @mikhail-vl ready for review

2024-10-28 13:28 UTC, asimonok requested changes

2024-10-28 13:28 UTC, asimonok commented on src/types/panel.ts
> +  fontSize: ColumnHeaderFontSize;
Please update types it's rather header settings 
`header: { fontSize, fontColor, backgroundColor }`

2024-10-28 13:28 UTC, asimonok commented on src/components/Table/components/TableHeaderCell/TableHeaderCell.tsx
> +            font-size: ${header.column.columnDef.meta?.config.appearance.fontSize};
size should be taken from grafana theme

2024-10-28 13:28 UTC, asimonok commented on src/types/table.ts
> +  LG = '18px',
please not to use absolute values because they can be changed. Please use lg,md, etc instead

2024-10-28 13:28 UTC, asimonok commented on src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
> +          <InlineField label="Background Color" className={styles.colorPickerContainer} labelWidth={20}>
editor is a duplication of font color. Please use a separated component for both settings

2024-10-29 11:20 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-10-30 01:55 UTC, mikhail-vl approved these changes
Looks good!

2024-10-30 01:55 UTC, merged