Add Sanitized HTML and Markdown column type
VolkovLabs/business-table pull request #154
Opened 2024-11-08 14:41 UTC by vitPinchuk

Resolves: #150

2024-11-08 19:31 UTC, mikhail-vl reviewed
@asimonok Can we rename `Auto` to `Text`. Or there are more to it?

2024-11-11 10:26 UTC, asimonok requested changes

2024-11-11 10:26 UTC, asimonok commented on provisioning/dashboards/panels.json
> +      "pluginVersion": "1.6.0",
pluginVersion shouldn't be saved in provisioned dashboards to make migration always working

2024-11-11 10:26 UTC, asimonok commented on src/components/Table/components/CellRenderer/LayoutCellRenderer.tsx
> +  const { replaceVariables } = tablePanelContext.useContext();
I would add current row as a scoped var

2024-11-14 12:23 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-11-14 17:38 UTC, mikhail-vl approved these changes
Looks great!

2024-11-14 17:38 UTC, merged