Update data source name to id
VolkovLabs/business-table pull request #156
Opened 2024-11-09 12:58 UTC by vitPinchuk

Resolves: #151

2024-11-11 10:28 UTC, asimonok requested changes

2024-11-11 10:28 UTC, asimonok commented on src/migration.ts
> +          datasource: normalizeDatasourceOptions(dataSources, normalizedGroup.update.datasource),
migration should be applied to nested object operations as well

2024-11-14 12:23 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-11-14 17:44 UTC, mikhail-vl approved these changes
Looks great!

2024-11-14 17:44 UTC, merged