Add show/hide header for table
VolkovLabs/business-table pull request #157
Opened 2024-11-09 14:35 UTC by vitPinchuk

Resolves: #139

2024-11-11 10:33 UTC, asimonok requested changes

2024-11-11 10:33 UTC, asimonok commented on src/utils/test.ts
> +  showHeader: true,
all options in test utils should be disabled to make test data is more clear and predictable due to necessary to enable particular options per test

2024-11-14 12:26 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-11-15 10:52 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-11-17 02:30 UTC, mikhail-vl approved these changes
Looks great!

2024-11-17 02:30 UTC, merged