Add boolean type and Switch editor
VolkovLabs/business-table pull request #171
Opened 2024-11-20 10:12 UTC by vitPinchuk

Resolves: #144

2024-11-20 13:43 UTC, vitPinchuk commented
@asimonok @mikhail-vl ready for review

2024-11-20 13:54 UTC, asimonok requested changes

2024-11-20 13:54 UTC, asimonok commented on src/components/Table/components/CellRenderer/BooleanCellRenderer.test.tsx
> +  Icon: (props: any) => {
Please do mocks similar to another tests. Reference - `src/components/editors/TablesEditor/TablesEditor.test.tsx`

2024-11-20 13:54 UTC, asimonok commented on src/components/Table/components/CellRenderer/BooleanCellRenderer.tsx
> +      {...TEST_IDS.booleanCellRenderer.icon.apply(value ? 'check-circle' : 'circle')}
I would keep the same test id and just check icon name on the element (add passing name to element in Icon mock)

2024-11-20 13:54 UTC, asimonok commented on src/constants.ts
> +    icon: createSelector((name: unknown) => String(name), 'data-testid'),
please specify test id to prevent colisions like `data-testid boolean-cell-renderer icon`

2024-11-21 11:41 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-11-22 01:42 UTC, mikhail-vl approved these changes
Looks good!

2024-11-22 01:42 UTC, merged